import { Product, Category } from './types';

export const categories: Category[] = [
  { id: 'motherboards', name: 'Tarjetas Madre', description: 'Placas base para laptops' },
  { id: 'ram', name: 'Memoria RAM', description: 'Módulos de memoria' },
  { id: 'storage', name: 'Almacenamiento', description: 'Discos duros y SSDs' },
  { id: 'screens', name: 'Pantallas', description: 'Pantallas LCD/LED' },
  { id: 'batteries', name: 'Baterías', description: 'Baterías para laptops' },
  { id: 'keyboards', name: 'Teclados', description: 'Teclados para laptops' },
  { id: 'cooling', name: 'Refrigeración', description: 'Ventiladores y sistemas de enfriamiento' },
];

export const initialProducts: Product[] = [
  {
    id: '1',
    name: 'Motherboard HP Pavilion',
    category: 'motherboards',
    price: 299.99,
    stock: 5,
    minStock: 3,
    description: 'Placa base compatible con HP Pavilion series',
    imageUrl: 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=500',
  },
  {
    id: '2',
    name: 'RAM DDR4 8GB',
    category: 'ram',
    price: 45.99,
    stock: 15,
    minStock: 5,
    description: 'Memoria RAM DDR4 8GB 2666MHz',
    imageUrl: 'https://images.unsplash.com/photo-1541029071515-84cc54f84dc5?w=500',
  },
  {
    id: '3',
    name: 'SSD 500GB',
    category: 'storage',
    price: 89.99,
    stock: 2,
    minStock: 4,
    description: 'Disco SSD 500GB SATA III',
    imageUrl: 'https://images.unsplash.com/photo-1597872200969-2b65d56bd16b?w=500',
  },
  {
    id: '4',
    name: 'Pantalla LED 15.6"',
    category: 'screens',
    price: 129.99,
    stock: 8,
    minStock: 3,
    description: 'Pantalla LED 15.6" Full HD 1920x1080',
    imageUrl: 'https://images.unsplash.com/photo-1544281679-57bc39fe592e?w=500',
  },
  {
    id: '5',
    name: 'Batería Dell Latitude',
    category: 'batteries',
    price: 79.99,
    stock: 12,
    minStock: 5,
    description: 'Batería original para Dell Latitude',
    imageUrl: 'https://images.unsplash.com/photo-1612815154858-60aa4c59eaa6?w=500',
  },
  {
    id: '6',
    name: 'Teclado Lenovo ThinkPad',
    category: 'keyboards',
    price: 49.99,
    stock: 6,
    minStock: 4,
    description: 'Teclado retroiluminado para Lenovo ThinkPad',
    imageUrl: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=500',
  },
  {
    id: '7',
    name: 'Ventilador CPU',
    category: 'cooling',
    price: 24.99,
    stock: 20,
    minStock: 8,
    description: 'Ventilador de CPU con disipador de calor',
    imageUrl: 'https://images.unsplash.com/photo-1587202372634-32705e3bf49c?w=500',
  },
  {
    id: '8',
    name: 'RAM DDR3 4GB',
    category: 'ram',
    price: 29.99,
    stock: 4,
    minStock: 5,
    description: 'Memoria RAM DDR3 4GB 1600MHz',
    imageUrl: 'https://images.unsplash.com/photo-1541029071515-84cc54f84dc5?w=500',
  },
];